
    <h2>Privacy Policy</h2>
<p>Information Collection. ZendoSpa LLC (hereafter 'RateStuf') is committed to protecting your privacy. The personal information collected is used for various purposes, including, but not limited to: responding to inquiries, processing applications, and billing.  Any changes to the Privacy Policy will be posted on this page to keep you aware of what information is collected, how it is used, and under what circumstances it will be disclosed.  It is your responsibility to review RateStuf&trade;’s Privacy Policy each time you provide personal information to RateStuf&trade; as the policy may have changed since the last time you used the site.</p>

<p>RateStuf&trade; does not sell, trade, or rent personal information to others. RateStuf&trade; may release account information when we believe, in good faith, that such release is reasonably necessary to (i) comply with law, (ii) enforce or apply the terms of any of our user agreements or (iii) protect the rights, property or safety of RateStuf&trade;, our participants or others. Every effort is made to keep users aware of how information is collected and kept secure.</p> 

<p>Consent To Processing of Personal Information.  By providing any Personal Information to RateStuf&trade;, all users unambiguously consent to this Privacy Policy and to the transfer of such Personal Information between various states and countries in accordance with RateStuf&trade;’s standard operations as necessary to accomplish and carryout the operations of RateStuf&trade;.</p>

<p>Protecting Your Information. While no Internet site can guarantee security, we use physical, electronic, and administrative safeguards to assist us in preventing unauthorized access, maintaining data accuracy, and correctly using your Personal Information. Except as specified in this Privacy Policy, we use commercially reasonable efforts to limit access to your Personal Information to the employees, agents, and officers of RateStuf&trade; who need the information to carry out their jobs.</p>

<p>Email notifications. If you wish to contact us via email, you will be asked to leave contact information, so that we can send you the requested information. The personal information, such as name, phone, email address, will solely be used for this purpose.</p> 

<p>Third-party website links. This policy only addresses RateStuf&trade;'s privacy policy concerning information collected from its own website and does not apply to information that may have been collected by others. This policy does not cover the privacy or information collection practices of third-party websites that may be linked to this website. Please be aware that when you leave this site, you should read the third-party website privacy practices before submitting personal information. RateStuf&trade; has no control or influence over third-party policies, and cannot be held liable for damage or misdoings of other websites linked or otherwise.</p>

<p>Your California Privacy Rights.  As provided by California Civil Code Section 1798.83, a California resident who has provided Personal Information to a business with whom they have established a business relationship for personal, family, or household purposes (“California customer”) is entitled to request information about whether the business has disclosed Personal Information to any third parties for the third parties’ direct marketing purposes. In general, if the business has made such a disclosure of Personal Information, upon receipt of a request by a California customer, the business is required to provide a list of all third parties to whom Personal Information was disclosed in the preceding calendar year, as well as a list of the categories of Personal Information that were disclosed.</p>

<p>California customers may request further information about our compliance with this law by emailing RateStuf&trade;.  Please note that we are only required to respond to one request per customer each year.</p>

<p>Information Use. Personal information relayed is used solely to facilitate, improve, and deliver services to our customers. When you contact us via email or by phone, we only use this information to respond to you. We do not share your personal information with outside parties, except where necessary to provide you with requested services or in an emergency situation.</p>

<p>&copy;<?php echo date('Y'); ?> RateStuf&trade; All rights reserved.</p>
